repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Use the latest version or specify a version
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.2  # Use the latest version or specify a version
    hooks:
      - id: ruff-format
      - id: ruff
        args:
          - --fix
